### PR TITLE
Update messages_es.yml

### PR DESCRIPTION
**Pull request by NekoShouta**
Correct some translation errors.

### CODE REVIEW

**Comment by AlessioDP** [comment]
Thank you :)
The translation changes a lot! Do you prefer update it for 2.3, so that I can remove the old one?

**Comment by NekoShouta** [comment]
Okay, tomorrow I'll translate the new one.

Sorry for the inconvenient :)

**Comment by AlessioDP** [comment]
Thank you for the translation! :)

**Comment by NekoShouta** [comment]
Can you please give me the untranslated phrases and the line number, so I don't have to translate all the phrases or search the untranslated ones?

**Comment by AlessioDP** [comment]
You can download the old one and do a git diff with the new one, you can find the new one here: 
https://github.com/AlessioDP/Parties/blob/master/bukkit/src/main/resources/bukkit/messages.yml

You cannot use history button because the directory has changed.

**Pull request closed without merging**
