### PR TITLE
Updated Simplified Chinese Transaltion

### PR DESCRIPTION
**Pull request by ahdg6**

### CODE REVIEW

**Comment by AlessioDP** [comment]
Translations are not handled manually in this repository, you must use the Crowdin page to send your translations:
https://crowdin.com/project/parties

**Comment by ahdg6** [comment]
I have no experience in using Crowdin,Can you help me with uploading it?

**Comment by AlessioDP** [comment]
Sure, firstly you need an account.
Then you can translate strings one by one or (recommended, because there are already some translations right now) or use the upload translation button, you can find it by clicking "Chinese Simplified" page.

**Comment by ahdg6** [comment]
I uploaded it just now,thank you.

**Pull request closed without merging**
